services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hrpwd
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr -d hrdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://db:5432/hrdb
      DB_USER: hr
      DB_PASSWORD: hrpwd
      TZ: Europe/Moscow
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
