spring:
  application:
    name: employment-service
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      request-connect-timeout: 5000
      request-read-timeout: 15000
      retry:
        max-attempts: 12
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000