server:
  port: 0
spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:postgresql://postgres:5432/unipeople
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: org
  flyway:
    enabled: true
    schemas: org
    locations: classpath:db/migration
  cloud:
    openfeign:
      circuitbreaker.enabled: true
      client:
        config:
          employee-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
resilience4j:
  circuitbreaker:
    instances:
      employeeClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
